### ISSUE TITLE
I would like to see a release for win 8.1 too

### ISSUE THREAD

**Issue by alptolga** [DeadManWalkingTO/Windows10MiningTweaksDmW#3]
I must say that your tweaks are really great but you always update it. So must we update too? There is no information in your releases. And also do you have any plan to make tweaks for win 8.1?

**Comment by DeadManWalkingTO** [comment]
I continually add new improvements.
You can simply update your version and run the Script again.

I don't plan to make Tweaks for Win 8.1? (I have never used the Windows 8.1).
Best Windows for mining = Win7 x64.
Best Windows for mining (6+ GPU) = Win10 x64.

If you have any suggestions about Win8.1 are very welcome.

**Comment by DeadManWalkingTO** [comment]
Any help/idea is welcome!
Thank you.
