### ISSUE TITLE
Explorer.exe not working normally

### ISSUE THREAD

**Issue by dahikino** [DeadManWalkingTO/Windows10MiningTweaksDmW#4]
I have issue with explorer.exee after execute all the tweak !
i can open shortcut of folders but not execute Explorer.exe.
how can i rollback this change ?

![image](https://user-images.githubusercontent.com/4519582/38337997-f486b324-3867-11e8-8657-93421f900d86.png)

![image](https://user-images.githubusercontent.com/4519582/38337909-9121efd8-3867-11e8-8c73-f2aa0778afaa.png)

**Comment by DeadManWalkingTO** [comment]
Give more information please.
Windows Version.
System Language.
Anti-virus Program.

**Comment by dahikino** [comment]
Windows 10 Profesional 1709, in French Language with Kaspersky KIS 2018 anti virus software :p
