### ISSUE TITLE
"Disable Quick Access as default view in Explorer" causes "Explorer.EXE Unknown Error"

### ISSUE THREAD

**Issue by Object380** [DeadManWalkingTO/Windows10MiningTweaksDmW#6]
"Disable Quick Access as default view in Explorer? y/n: " with "LaunchTo = 0" setting causes "Explorer.EXE Unknown Error" in Windows 10 x64 1709
![screenshot_12](https://user-images.githubusercontent.com/37984567/38732336-7d3c518c-3f26-11e8-9768-b1eaf0b5aaa4.png)

**Comment by erkange** [comment]
same for me.
